[2022-08-23 00:00:04,314] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2022-08-23 00:00:04,333] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2022-08-23 00:00:04,334] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 00:00:04,336] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-23 00:00:04,337] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 00:00:04,363] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): create_table> on 2022-08-22 00:00:00+00:00
[2022-08-23 00:00:04,371] {standard_task_runner.py:52} INFO - Started process 92664 to run task
[2022-08-23 00:00:04,382] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'scheduled__2022-08-22T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/user-processing.py', '--cfg-path', '/tmp/tmpfv6s6t5o', '--error-file', '/tmp/tmpyp8w5qvh']
[2022-08-23 00:00:04,385] {standard_task_runner.py:80} INFO - Job 11: Subtask create_table
[2022-08-23 00:00:04,521] {task_command.py:371} INFO - Running <TaskInstance: user_processing.create_table scheduled__2022-08-22T00:00:00+00:00 [running]> on host 6eab8cd56147
[2022-08-23 00:00:04,838] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-08-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-22T00:00:00+00:00
[2022-08-23 00:00:04,885] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-08-23 00:00:04,908] {dbapi.py:231} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
        , parameters: None
[2022-08-23 00:00:04,917] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2022-08-23 00:00:04,988] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20220822T000000, start_date=20220823T000004, end_date=20220823T000004
[2022-08-23 00:00:05,490] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-23 00:00:05,804] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
