[2022-08-23 00:00:41,319] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: user_processing.store_user scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2022-08-23 00:00:41,370] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: user_processing.store_user scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2022-08-23 00:00:41,372] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 00:00:41,376] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-23 00:00:41,377] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-23 00:00:41,440] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): store_user> on 2022-08-22 00:00:00+00:00
[2022-08-23 00:00:41,458] {standard_task_runner.py:52} INFO - Started process 92883 to run task
[2022-08-23 00:00:41,470] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'store_user', 'scheduled__2022-08-22T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/user-processing.py', '--cfg-path', '/tmp/tmpuklvwoir', '--error-file', '/tmp/tmp5gyk7f5v']
[2022-08-23 00:00:41,482] {standard_task_runner.py:80} INFO - Job 15: Subtask store_user
[2022-08-23 00:00:41,849] {task_command.py:371} INFO - Running <TaskInstance: user_processing.store_user scheduled__2022-08-22T00:00:00+00:00 [running]> on host 6eab8cd56147
[2022-08-23 00:00:42,516] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=store_user
AIRFLOW_CTX_EXECUTION_DATE=2022-08-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-22T00:00:00+00:00
[2022-08-23 00:00:42,523] {postgres.py:127} INFO - Running copy expert: COPY users FROM stdin WITH DELIMITER as ',', filename: /tmp/processed_user.csv
[2022-08-23 00:00:42,579] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-08-23 00:00:42,616] {python.py:173} INFO - Done. Returned value was: None
[2022-08-23 00:00:42,678] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=store_user, execution_date=20220822T000000, start_date=20220823T000041, end_date=20220823T000042
[2022-08-23 00:00:42,797] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-23 00:00:42,963] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
